version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    container_name: '${APP_NAME}'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: yarn start:dev
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mariadb
    networks:
      - backend

  mariadb:
    image: mariadb:${DB_VERSION}
    container_name: '${APP_NAME}_mariadb'
    restart: 'always'
    environment:
      ## Note: all of these environment variables can also be loaded from .env

      MYSQL_DATABASE: '${DB_DATABASE}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${DB_USERNAME}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      # Good for testing, but not production
      MYSQL_ALLOW_EMPTY_PASSWORD: '${DB_ALLOW_EMPTY_PASSWORD}'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      # default is:
      #- '3306:3306'
      - '${DB_PORT}:${DB_PORT}'
    expose:
      # Opens port 3306 on the container
      # default is:
      #- '3306'
      - '${DB_PORT}'
      # Where our data will be persisted
    volumes:
      - mysql:/data/mysql
    networks:
      - backend

volumes:
  mysql:
    driver: local

networks:
  backend:
    driver: bridge
